#!/usr/local/bin/bash

EXPORT=/tmp/dependencies.tar

cd /
tar -cf ${EXPORT} dev/null
for file in $bin $(/root/ldd-rec.py $@); do
    tar -uf ${EXPORT} $(echo $file | sed -e 's/^\///')
#   tar -uf ${EXPORT} $(readlink -f $file | sed -e 's/^\///')
done
tar --delete -f ${EXPORT} dev/null
tar -tvf ${EXPORT}
