#!/usr/local/bin/bash

EXPORT=/tmp/dependencies.tar
WORKDIR=$(pwd)

set -x

cd /
tar -cf ${EXPORT} dev/null
for file in $bin $($WORKDIR/ldd-rec.py $@); do
    tar -uf ${EXPORT} $(echo $file | sed -e 's/^\///')
#   tar -uf ${EXPORT} $(readlink -f $file | sed -e 's/^\///')
done
tar -tvf ${EXPORT}
