#!/bin/sh

# Create all the symlinks to /bin/busybox
/bin/busybox mkdir -p /bin /sbin /etc /proc /sys /newroot /usr/bin /usr/sbin
/bin/busybox --install -s

sleep .5

cat <<EOF

Welcome to Scaleway' initrd

███████╗ ██████╗ █████╗ ██╗     ███████╗██╗    ██╗ █████╗ ██╗   ██╗
██╔════╝██╔════╝██╔══██╗██║     ██╔════╝██║    ██║██╔══██╗╚██╗ ██╔╝
███████╗██║     ███████║██║     █████╗  ██║ █╗ ██║███████║ ╚████╔╝
╚════██║██║     ██╔══██║██║     ██╔══╝  ██║███╗██║██╔══██║  ╚██╔╝
███████║╚██████╗██║  ██║███████╗███████╗╚███╔███╔╝██║  ██║   ██║
╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚══════╝ ╚══╝╚══╝ ╚═╝  ╚═╝   ╚═╝

http://j.mp/scw-initrd-linux                ZCOMMIT - ZDATE_____

EOF

# prepare a tmpfs-based initramfs for shutdown
mkdir /initramfs
cp -rf / /initramfs 2>/dev/null


# Mount things needed by this script
[ -d /dev ] || mkdir -m 0755 /dev
mount -t devtmpfs -o mode=0755 none /dev
mkdir /dev/pts
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 none /dev/pts

[ -d /run ] || mkdir -pm 0755 /run
mount -t tmpfs -o mode=0755,nodev,nosuid,size=10% tmpfs /run
[ -d /var ] || mkdir -pm 0755 /var
ln -s /run /var/run

[ -d /sys ] || mkdir /sys
mount -t sysfs -o nodev,noexec,nosuid none /sys

[ -d /proc ] || mkdir /proc
mount -t proc -o nodev,noexec,nosuid none /proc


# Loading functions
. /functions


# Configure GPIOs
setup_gpios


# Initial /proc/cmdline parsing
export METADATA_IP=$(get_opt METADATA_IP 169.254.42.42)


# Configure network
log_begin_msg "Configuring network"
ifconfig eth0 up
udhcpc -n -q -i eth0
log_end_msg


# Verbose mode
log_begin_msg "Checking user input for debug mode"
if [ "$(get_any INITRD_DEBUG)" = "1" ]; then
    log_success_msg "Enabling initrd debug"
    log_end_msg
    set -x
    env
else
    log_end_msg
fi


# Drop debug shell
log_begin_msg "Checking user input for debug shell"
if [ "$(get_any INITRD_PRE_SHELL)" = "1" ]; then
    log_success_msg "Dropping a debug shell"
    log_end_msg
    echo "**DEBUG SHELL** (requested from the user)"
    echo "To continue the initrd process, just type C^d"
    /bin/sh
else
    log_end_msg
fi


# Signal to the console that the kernel is started
signal_state kernel-started


# Adjust time
if [ "$(get_any NO_NTPDATE)" != "1" ]; then
    log_begin_msg "Adjusting time (ntp)"
    NTPSRV=$(cat /etc/ntpsrv)
    ntpdate -d -b -p 2 "${NTPSRV}" >/dev/null 2>&1 | tr '\r\n' '  '
    ntpdate -d -b -p 6 "${NTPSRV}" >/dev/null 2>/dev/null &
    log_end_msg
fi


# Defaults
init=$(get_any init "/sbin/init")
root=$(get_any root "/dev/nbd0")
default_boot="local"
if [ "${root}" = "/dev/nfs" ]; then
    default_boot="nfs"
fi
boot=$(get_any boot "${default_boot}")
rootmnt=$(get_any rootmnt "/newroot")


# Import boot-type functions
case "${boot}" in
    local)
        . ./boot-nbd
        ;;
    rescue)
        . ./boot-rescue
        ;;
    nfs)
        . ./boot-nfs
        ;;
    live)
        . ./boot-live
        ;;
    *)
	. ./boot-fallback
	;;
esac


# Mountroot
mountroot


# Signal to the console that the server is booted
signal_state booted


# Forward network configuration files
mkdir -p ${rootmnt}/etc
touch ${rootmnt}/etc/hostname ${rootmnt}/etc/resolv.conf
[ -s ${rootmnt}/etc/hostname ] || oc-metadata --cached HOSTNAME > ${rootmnt}/etc/hostname
grep $(grep ^nameserver /etc/resolv.conf | head -1 | awk '{print $2}') ${rootmnt}/etc/resolv.conf >/dev/null || cat /etc/resolv.conf >> ${rootmnt}/etc/resolv.conf


# Drop debug shell
log_begin_msg "Checking metadata for debug shell"
if [ "$(get_any INITRD_POST_SHELL)" = "1" ]; then
    log_success_msg "Dropping a debug shell"
    log_end_msg
    echo "**DEBUG SHELL** (requested from the TAGS metadata of the server)"
    echo "To continue the initrd process, just type C^d"
    /bin/sh
else
    log_end_msg
fi


# Drop debug shell
log_begin_msg "Checking metadata for debug sshd (dropbear)"
if [ "$(get_any INITRD_DROPBEAR)" = "1" ]; then
    log_success_msg "Starting a debug sshd"
    start_sshd
    log_end_msg
    echo "**DEBUG DROPBEAR** (requested from the TAGS metadata of the server)"
    echo "To continue the initrd process, just type 'echo 1 > /continue' from the ssh server"
    # FIXME: display ssh command and scw command
    # FIXME: display common usages (luks, lvm, etc) in a README.txt file
    mkfifo /continue
    cat /continue
else
    log_end_msg
fi


# Ensure sshd is killed if running
killall dropbear &>/dev/null
# FIXME: if host keys don't exist in /newroot (first boot), we can copy the generated ones


# Prepare mount pseudo filesystem moving
mkdir -p ${rootmnt}/run ${rootmnt}/sys ${rootmnt}/dev ${rootmnt}/proc
mount -o move /proc ${rootmnt}/proc
mount -o move /sys ${rootmnt}/sys
mount -o move /run ${rootmnt}/run
mount -o move /dev ${rootmnt}/dev
[ -c ${rootmnt}/dev/console ] || mknod -m 622 ${rootmnt}/dev/console c 5 1
[ -c ${rootmnt}/dev/null ] || mknod -m 666 ${rootmnt}/dev/null c 1 3
[ -c ${rootmnt}/dev/zero ] || mknod -m 666 ${rootmnt}/dev/zero c 1 5
[ -c ${rootmnt}/dev/ptmx ] || mknod -m 666 ${rootmnt}/dev/ptmx c 5 2
[ -c ${rootmnt}/dev/tty ] || mknod -m 666 ${rootmnt}/dev/tty c 5 0
[ -c ${rootmnt}/dev/random ] || mknod -m 444 ${rootmnt}/dev/random c 1 8
[ -c ${rootmnt}/dev/urandom ] || mknod -m 444 ${rootmnt}/dev/urandom c 1 9
# chown -v root:tty /dev/{console,ptmx,tty}


# Move initramfs copy to /run/initramfs for shutdown
mv /initramfs ${rootmnt}/run/initramfs


# Check if $init exists and is executable
if [[ -x "${rootmnt}/${init}" ]] ; then
    # Unmount all other mounts so that the ram used by
    # the initramfs can be cleared after switch_root
    # umount /sys /proc

cat <<EOF
End of Scaleway' initrd
           _ _       _      _          _ _
 ___ _ _ _|_| |_ ___| |_   | |_ ___   | |_|___ _ _ _ _ 
|_ -| | | | |  _|  _|   |  |  _| . |  | | |   | | |_'_|
|___|_____|_|_| |___|_|_|  |_| |___|  |_|_|_|_|___|_,_|
EOF

    # Switch to the new root and execute init
    exec switch_root "${rootmnt}" "${init}"
fi


# This will only be run if the exec above failed
echo "Failed to switch_root, dropping to a shell"
exec /bin/sh
