#!/bin/sh

set -x


# usage: /run/initramfs/shutdown {reboot|poweroff|halt}
ACTION="${1:-reboot}"


# FIXME: we may be called from systemd or another system, so each commands
#        should be able to fail without stopping the shutdown process


# disable hotplug kernel hook
echo > /proc/sys/kernel/hotplug


# umount special fs to allow pivot_root
umount /sys  &>/dev/null || umount -l /sys
umount /proc &>/dev/null || umount -l /proc
umount /dev  &>/dev/null || umount -l /dev


# pivot_root to initramfs
mkdir -p /run/initramfs/oldroot
PATH=/run/initramfs/bin /run/initramfs/bin/busybox pivot_root /run/initramfs /run/initramfs/oldroot
cd /


# here we are in the initramfs
mount -t proc -o nodev,noexec,nosuid none /proc
mount -t devtmpfs -o mode=0755 none /dev
ln -s /proc/mounts  /etc/fstab
swapoff -a


# for each NBD devices, we, ro-remount, umount and detach
for device in /dev/nbd[0-9]*; do mount -o remount,ro "${device}"; done
for device in /dev/nbd[0-9]*; do umount "${device}" &>/dev/null || umount -l "${device}"; done
for device in /dev/nbd[0-9]*; do /usr/sbin/xnbd-client -d "${device}"; done


# send sysrq
case "${ACTION}" in
    reboot)    reboot -f;    break;;
    poweroff)  poweroff -f;  break;;
    halt)      halt -f;      break;;
esac


# this should never happen
/bin/sh
