#!/bin/sh

ACTION="${1:-halt}"


# disable hotplug
echo > /proc/sys/kernel/hotplug


# here we are in the initramfs
ln -s /proc/mounts  /etc/fstab
swapoff -a


# unmount nbd devices
for device in $(mount | grep nbd | awk '{print $1}'); do
    umount $device &>/dev/null || umount -l $device
done


# detach nbd devices
for device in $(seq 0 15); do
    xnbd-client -d /dev/nbd${device} &>/dev/null
done


# send sysrq
case "${ACTION}" in
    reboot)    reboot -f;    break;;
    poweroff)  poweroff -f;  break;;
    halt)      halt -f;      break;;
esac


# this should never happen
/bin/sh
